#!/bin/sh
#
# Copyright 2019 Association for the promotion of open-source insurance software and for the establishment of open interface standards in the insurance industry (Verein zur Förderung quelloffener Versicherungssoftware und Etablierung offener Schnittstellenstandards in der Versicherungsbranche)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

REPOSPATH=$1
REV=$2

REPOSNAME=`basename "$REPOSPATH"`
COMMITTER=`svnlook author -r "$REV" "$REPOSPATH" | tr '[:upper:]' '[:lower:]'`
LOGFILE=/var/subversion/mergetrigger/logs/"$REPOSNAME"-r"$REV"_mergetrigger.log

#start the mergetrigger script
/usr/bin/perl /var/subversion/mergetrigger/scripts/mergetrigger_merge.pl "$REPOSPATH" "$REV" 1>"$LOGFILE" 2>&1

echo "Finished Merge Trigger"
